input {
  beats { port => 5044 }
}

filter {
  json {
    source => "message"
    target => "event_data"
  }
  date {
    match => ["[event_data][timestamp]", "ISO8601"]
    target => "@timestamp"
  }
  mutate {
    add_field => { "[event][dataset]" => "offline_service_desk.release_lab" }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "offline-service-desk-release-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
